CAMERA_INDEX = 0

DETECTION_CONFIDENCE = 0.6
TRACKING_CONFIDENCE = 0.6

ACTION_COOLDOWN = 1.0

WINDOW_NAME = "AI Hand Gesture Controller"

GESTURES = [
    "THUMBS UP",
    "THUMBS DOWN",
    "TWO FINGERS",
    "FIST",
    "ONE FINGER",
    "OPEN PALM"

